/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProcesarDatos;

/**
 *
 * @author Supre
 */
public class PanelDePresemtacionDeDatos extends javax.swing.JFrame {

    /**
     * Creates new form PanelDePresemtacionDeDatos
     */
    public PanelDePresemtacionDeDatos() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        presentarMatriculaField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        presentarCorreoField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        presentarNombreField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        presentarApellidoField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Presentacion de Datos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        presentarMatriculaField.setBackground(new java.awt.Color(255, 255, 255));
        presentarMatriculaField.setForeground(new java.awt.Color(0, 0, 0));
        presentarMatriculaField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        presentarMatriculaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presentarMatriculaFieldActionPerformed(evt);
            }
        });
        jPanel1.add(presentarMatriculaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 80, 30));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Matricula: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        presentarCorreoField.setBackground(new java.awt.Color(255, 255, 255));
        presentarCorreoField.setForeground(new java.awt.Color(0, 0, 0));
        presentarCorreoField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        presentarCorreoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presentarCorreoFieldActionPerformed(evt);
            }
        });
        jPanel1.add(presentarCorreoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 80, 30));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Correo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        presentarNombreField.setBackground(new java.awt.Color(255, 255, 255));
        presentarNombreField.setForeground(new java.awt.Color(0, 0, 0));
        presentarNombreField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        presentarNombreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presentarNombreFieldActionPerformed(evt);
            }
        });
        jPanel1.add(presentarNombreField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 80, 30));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        presentarApellidoField.setBackground(new java.awt.Color(255, 255, 255));
        presentarApellidoField.setForeground(new java.awt.Color(0, 0, 0));
        presentarApellidoField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        presentarApellidoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presentarApellidoFieldActionPerformed(evt);
            }
        });
        jPanel1.add(presentarApellidoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 80, 30));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Apellido:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void presentarMatriculaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presentarMatriculaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_presentarMatriculaFieldActionPerformed

    private void presentarCorreoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presentarCorreoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_presentarCorreoFieldActionPerformed

    private void presentarNombreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presentarNombreFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_presentarNombreFieldActionPerformed

    private void presentarApellidoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presentarApellidoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_presentarApellidoFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelDePresemtacionDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelDePresemtacionDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelDePresemtacionDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelDePresemtacionDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelDePresemtacionDeDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField presentarApellidoField;
    private javax.swing.JTextField presentarCorreoField;
    private javax.swing.JTextField presentarMatriculaField;
    private javax.swing.JTextField presentarNombreField;
    // End of variables declaration//GEN-END:variables
}
